### ISSUE TITLE
关于vocab_idx的形式

### ISSUE THREAD

**Issue by victory-hsu** [KnightZhang625/Enhanced-RCNN_TensorFlow#3]
您好，请教一下，您的数据集的形式结构，以及vocab_idx的形式，是否有按照词频降序之类的操作等

**Comment by victory-hsu** [comment]
> 您好，请教一下，您的vocab_idx是否是跟bert一样的结构，有cls,和sep标记符？

**Comment by KnightZhang625** [comment]
Data: a list contains (que, ans)s of tuple type. You could find how I create the vocab_idx from the beginning of the load_data.py, no term-frequency is used.
