### ISSUE TITLE
请教一下作者，train的时候是问答对，inference的时候是单独的一个问题，两阶段任务是不一致的，是否会有影响？

### ISSUE THREAD

**Issue by victory-hsu** [KnightZhang625/Enhanced-RCNN_TensorFlow#4]

**Comment by KnightZhang625** [comment]
我的理解是，这个任务infer的时候也需要输入两个句子进行相似度匹配。一个问题，你也需要把库里所有的句子和他做一遍相似度计算。

**Comment by victory-hsu** [comment]
> 我的理解是，这个任务infer的时候也需要输入两个句子进行相似度匹配。一个问题，你也需要把库里所有的句子和他做一遍相似度计算。

谢谢作者，我之前的理解是可以把知识库内的问题向量写入到array中，存储起来，inference的时候把是实时的问题转化为向量，基于这个向量，在array中找到最想似的数据库问题，总感觉这样理解的话，训练与推理是不一样的！

**Comment by KnightZhang625** [comment]
这个模型的架构看起来是无法这样做的。

**Comment by victory-hsu** [comment]
> 这个模型的架构看起来是无法这样做的。

嗯嗯~~~
